dream/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tracker/', include('tracker.urls', namespace="tracker")),
]

tracker/urls.py
from django.conf.urls import url
from tracker import views

urlpatterns = [
		url(r'^$',views.home , name='home'),
		url(r'^(?P<project_sname>\w+)/summary$',views.project_summary , name='project_summary'),
		]

tracker/models.py
from django.db import models


class Project_Info(models.Model):
	Project_Name		= models.CharField(max_length=30, help_text="Project Name")
	Project_Short_Name	= models.CharField(max_length=10, help_text="Project Short Name", primary_key=True)
	Project_Manager		= models.CharField(max_length=30, help_text="Project Manager Name")
	Project_Architect	= models.CharField(max_length=30, help_text="Project Architect Name")

	def __str__(self):
		return self.Project_Name

class Project_Stream_Table(models.Model):
	class Meta:
		unique_together=(('Project_Short_Name','Project_Stream'),)

	#Project_Short_Name			= models.CharField(max_length=10, help_text="Project Short Name", primary_key=True)
	Project_Short_Name			= models.ForeignKey(Project_Info)
	Project_Stream				= models.CharField(max_length=10, help_text="Stream Name")
	Project_Release_Label			= models.CharField(max_length=10, help_text="Release Label")
	Project_Release_Label_Date		= models.DateField(help_text="Released Date",blank=True, null=True)
	Project_Release_Label_inprogress	= models.CharField(max_length=10, help_text="Draft Release Label",blank=True, null=True)
	Project_Release_Label_Date_inprogress	= models.DateField(help_text="Draft Release Date",blank=True, null=True)


	def __str__(self):
		return '%s stream for %s' % (self.Project_Stream , self.Project_Short_Name)

tracker/forms.py
from django.forms import ModelForm
from tracker.models import Project_Stream_Table, CRQtable, Releasetable

class Project_Stream_Table_Form(ModelForm):
	class Meta:
		model = Project_Stream_Table
		fields = ['Project_Stream']

tracker/views.py
from django.shortcuts import render
from tracker.models import Project_Info, Project_Stream_Table


def home(request):
	context_param = {}
	#projects = Project_Info.objects.all().order_by("Project_Name")
	#context_param['projects'] = projects

	return render(request, 'tracker/home.html', context_param)

def project_summary(request, project_sname):
	context_param = {}
	print (project_sname)

	try:
		project = Project_Info.objects.get(Project_Short_Name=project_sname)
		context_param['project'] = project

		streams = Project_Stream_Table.objects.filter(Project_Short_Name = project)
		context_param['streams'] = streams

	except Project_Info.DoesNotExist:
		pass

	return render(request, 'tracker/project_summary.html', context_param) 

templates/tracker/add_stream.html
<!DOCTYPE html>

{% extends 'tracker/base.html' %}

{% load staticfiles %}

{% block title_block %}Add Stream{% endblock title_block %}

{% block page_hdr %}Add Stream{% endblock page_hdr %}

{% block release_detail %}

<form method="POST" action="#">
{% csrf_token %}



{% if error_message %}
<div class="alert alert-warning">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong>Warning!</strong> {{ error_message }}
</div>
{% endif %}

{{ addSForm.as_p }}

<input type="submit" text="Create Stream">
</form>

{% endblock release_detail %}

templates/tracker/base.html
<!DOCTYPE html>

<{% load tracker_extras %}

<!-- saved from url=(0045)https://getbootstrap.com/examples/dashboard/# -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="Ashwani Mishra">
    <link rel="icon" href="https://getbootstrap.com/favicon.ico">

    <title>Tracker-{% block title_block %}Base{% endblock title_block %}</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href="./Dashboard Template for Bootstrap_files/bootstrap.min.css" rel="stylesheet"> -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'tracker:home' %}">Tracker</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul> 
	{% block side_block %}
		{% get_project_list project %}
	{% endblock %}
	{% block project_fav_list %}
	<ul class="nav nav-sidebar">
            <li><a href="#">Nav item</a></li>
            <li><a href="#">Nav item again</a></li>
            <li><a href="#">One more nav</a></li>
            <li><a href="#">Another nav item</a></li>
            <li><a href="#">More navigation</a></li>
          </ul>
	{% endblock project_fav_list %}
          <ul class="nav nav-sidebar">
            <li><a href="#">Nav item again</a></li>
            <li><a href="#">One more nav</a></li>
            <li><a href="#">Another nav item</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">{% block page_hdr %}Dashboard{% endblock page_hdr %}</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label1</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label2</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label3</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label4</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Release Details</h2>
          <div class="table-responsive">
{% block project_release_detail %} 
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Stream</th>
                  <th>Last Release Id</th>
                  <th>Last Release Date</th>
                  <th>Ongoing Release Id</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
              </tbody>
            </table>
{% endblock project_release_detail %} 
          </div>
	<h2 class="sub-header">Change Request Details</h2>
          <div class="table-responsive">
{% block project_change_detail %} 
           <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>CRQ Id</th>
                  <th>Stream</th>
                  <th>Stage</th>
                  <th>Delivery Date</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
              </tbody>
            </table>
{% endblock project_change_detail %}
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src=".https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="http://getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src=".http://getbootstrap.com/assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  

</body></html>

templates/tracker/base_rango.html
<!DOCTYPE html>

{% load rango_extras %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="Ashwani">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">
	
    <title>Rango - {% block title_block %}How to Tango with Django!!{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/rango/">Rango</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
			<li><a href="{% url 'rango:index' %}">Home</a></li>
				{% if user.is_authenticated %}
					<li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
					<li><a href="{% url 'accounts:auth_logout' %}?next=/rango/">Logout</a><br /></li>
					<li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
				{% else %}
					<li><a href="{% url 'accounts:registration_register' %}">Register Here</a></li>
					<li><a href="{% url 'accounts:auth_login' %}">Login</a></li>
				{% endif %}
			<li><a href="{% url 'rango:about' %}">About</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
			{% block side_block %}
				{% get_category_list category %}
			{% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<div>
				{% block body_block %}{% endblock %}
			</div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="http://getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src=".http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="http://getbootstrap.com/assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/tracker/crq_details.html
<!DOCTYPE html>

{% extends 'tracker/base.html' %}

{% load staticfiles %}

{% block title_block %}Change Details{% endblock title_block %}

{% block page_hdr %}{{ header }}{% endblock page_hdr %}

{% block release_detail %}	

{% if crq %}
     <h2 class="sub-header">Change Details</h2>
       <div class="table-responsive">
	<table class="table table-striped">              
              <tbody>	
                <tr>
                  <td>CRQ Id</td>
                  <td>Stream Name</td>
                  <td>Stage</td>
                </tr>
		
                <tr>
                  <td>{{ crq.CRQid }}</td>
                  <td>{{ crq.Project_Stream }}</td>
                  <td>{{ crq.Stage }}</td>
                </tr>

		<tr>
                  <td>Architect/BA</td>
                  <td>Architect Start Time</td>
                  <td>Architect End Time</td>
                </tr>
		<tr>
                  <td>{{ crq.Architect_BAName }}</td>
                  <td>{{ crq.Req_DesStartDate }}</td>
                  <td>{{ crq.Req_DesCompletionDate }}</td>
                </tr>
		
                <tr>
                  <td>FRS</td>
                  <td>Design</td>
                  <td></td>
                </tr>		
                <tr>
                  <td>{{ crq.FRS_link }}</td>
                  <td>Design</td>
                  <td></td>
                </tr>
		
                <tr>
                  <td>Developer</td>
                  <td>Development Start Date</td>
                  <td>Development End Date</td>
                </tr>
		
                <tr>
                  <td>{{ crq.DeveloperName }}</td>
                  <td>{{ crq.DevStartDate }}</td>
                  <td>{{ crq.DevCompletionDate }}</td>
                </tr>
		
                <tr>
                  <td>Object Package</td>
                  <td>Release Note</td>
                </tr>
		
                <tr>
                  <td>{{ crq.ObjectPackagelink }}</td>
                  <td>{{ crq.ReleaseNotelink }}</td>
                </tr>

		<tr>
                  <td>Tester</td>
                  <td>Testing Start Date</td>
		  <td>Testing End Date</td>
                </tr>
		<tr>
                  <td>{{ crq.TesterName }}</td>
                  <td>{{ crq.TestStartDate }}</td>
                  <td>{{ crq.TestCompletionDate }}</td>
                </tr>
		
                <tr>
                  <td>Test Case</td>
                  <td>Test Result</td>
                </tr>
		
                <tr>
                  <td>{{ crq.TestCaselink }}</td>
                  <td>{{ crq.TestResultlink }}</td>
                </tr>
		
                <tr>
                  <td>Delivery Date</td>
                  <td>{{ crq.DeliveryDate }}</td>
                </tr>
              </tbody>
        </table>
	</div>
{% else %}
<strong>
Currently this project has no Change request information. You will need to add a new CR to see in list.
</strong>
{% endif %}

<br><br>
<div class="container-fluid">
  <a href="#" class="btn btn-info" role="button">Add Stream</a>&nbsp&nbsp&nbsp&nbsp
  <a href="#" class="btn btn-info" role="button">New Change Request</a>
</div>
<hr>

{% endblock release_detail %}

templates/tracker/home.html
<!DOCTYPE html>

{% extends 'tracker/base.html' %}

{% load staticfiles %}

{% block title_block %}Home{% endblock title_block %}

{% block page_hdr %}Home{% endblock page_hdr %}

templates/tracker/project_summary.html
<!DOCTYPE html>

{% extends 'tracker/base.html' %}

{% load staticfiles %}

{% block title_block %}{{ project.Project_Name }} Detail{% endblock title_block %}

{% block page_hdr %}{{ project.Project_Name }}{% endblock page_hdr %}

{% block project_release_detail %}

{% if streams %}

	<table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Stream</th>
                  <th>Last Release Id</th>
                  <th>Last Release Date</th>
                  <th>Ongoing Release Id</th>
                </tr>
              </thead>
              <tbody>
   {% for stream in streams %}
	
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ stream.Project_Stream }}</td>
                  <td>{{ stream.Project_Release_Label }}</td>
                  <td>{{ stream.Project_Release_Label_Date }}</td>
                  <td>{{ stream.Project_Release_Label_inprogress }}</td>
                </tr>
  {% endfor %}
              </tbody>
        </table>
{% endif %}
	
{% endblock project_release_detail %}

templates/tracker/projectlist.html
{% if Projects %}
	<ul class="nav nav-sidebar">
		{% for project in Projects %}
			{% if project == act_project %}
				<li class="active"><a href="{% url 'tracker:project_summary' project.Project_Short_Name %}">a{{ project.Project_Name }}</a></li>
			{% else %}
				<li><a href="{% url 'tracker:project_summary' project.Project_Short_Name %}">{{ project.Project_Name }}</a></li>
			{% endif %}
		{% endfor %}
	</ul>
{% else %}	
	<ul class="nav nav-sidebar">
		<li><strong>There is no project present.</strong></li>
	</ul>
{% endif %}

templates/tracker/release_details.html
<!DOCTYPE html>

{% extends 'tracker/base.html' %}

{% load staticfiles %}

{% block title_block %}Release Details{% endblock title_block %}

{% block page_hdr %}{{ header }}{% endblock page_hdr %}

{% block release_detail %}	

{% if release %}
     <h2 class="sub-header">Release Details</h2>
       <div class="table-responsive">
	<table class="table table-striped">              
              <tbody>	
                <tr>
                  <td>Release Label</td>
                  <td>{{ release.ReleaseId }}</td>
                </tr>
		
                <tr>
                  <td>Stream Name</td>
                  <td>{{ release.Project_Stream }}</td>
                </tr>
		
                <tr>
                  <td>Initiation Date</td>
                  <td>{{ release.InitiationDate }}</td>
                </tr>
		
                <tr>
                  <td>Completion Date</td>
                  <td>{{ release.CompletionDate }}</td>
                </tr>
		
                <tr>
                  <td>FRS</td>
                  <td>{{ release.FRS_link }}</td>
                </tr>
		
                <tr>
                  <td>SVN</td>
                  <td>{{ release.SVN_link }}</td>
                </tr>
		
                <tr>
                  <td>Change Requests</td>
                  <td>{{ release.Linked_CRQid }}</td>
                </tr>
		
                <tr>
                  <td>Release Initiator</td>
                  <td>{{ release.Initiator_User }}</td>
                </tr>
		
                <tr>
                  <td>Initiation Completion Date</td>
                  <td>{{ release.Initiator_Timeline }}</td>
                </tr>
		
                <tr>
                  <td>Release Manager</td>
                  <td>{{ release.Manager_User }}</td>
                </tr>
		
                <tr>
                  <td>Review Completion Date</td>
                  <td>{{ release.Manager_timeline }}</td>
                </tr>
		
                <tr>
                  <td>Release Approver</td>
                  <td>{{ release.Approver_User }}</td>
                </tr>
		
                <tr>
                  <td>Approval Completion Date</td>
                  <td>{{ release.Approver_timeline }}</td>
                </tr>
              </tbody>
        </table>
	</div>
{% else %}
<strong>
Currently this project has no Change request information. You will need to add a new CR to see in list.
</strong>
{% endif %}

<br><br>
<div class="container-fluid">
  <a href="#" class="btn btn-info" role="button">Add Stream</a>&nbsp&nbsp&nbsp&nbsp
  <a href="#" class="btn btn-info" role="button">New Change Request</a>
</div>
<hr>

{% endblock release_detail %}